// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'tables': string;
  'teams': string;
  'teamsContainer': string;
  'teamsTables': string;
}
export const cssExports: CssExports;
export default cssExports;
