// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menuTrigger': string;
  'open': string;
}
export const cssExports: CssExports;
export default cssExports;
